name = "gitdash"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_GITHUB_USERNAME_PERSONAL = "rangersnuggles"
NEXT_PUBLIC_GITHUB_USERNAME_BUSINESS = "messrobrob"
GITHUB_USERNAME_PERSONAL = "rangersnuggles"
GITHUB_USERNAME_BUSINESS = "messrobrob"
NEXT_PUBLIC_SUPABASE_URL = "https://tfnhufwiqxulcbdvesxi.supabase.co"
